### PR TITLE
Improve formulae

### PR DESCRIPTION
**Pull request by rgov**
**Edit: This patch has been rewritten, see [below](https://github.com/tfcollins/homebrew-formulae/pull/9#issuecomment-731644176).**

This is a quick and dirty patch to change the formulae to build keg-only. On recent systems, Homebrew does not seem to be allowed to copy into /Library/Frameworks, so this forces them to build inside their Homebrew keg.

Unfortunately I ran out of time to work on actually fixing IIO Oscilloscope.

### CODE REVIEW

**Comment by tfcollins** [comment]
What brew and macOS versions are you building off? Tests fail in Catalina for me.
-Travis

**Comment by rgov** [comment]
I am on Big Sur, with Homebrew 2.5.11-6-g9f45814.

Sorry, this was kind of a phoned-in pull request because I had to give up and move on, and it requires some tweaking.

I see in TravisCI you are just installing the .pkg releases from analog.com for `libiio` and `libad9361-iio`, rather than testing the build from this repo's formulae. I only modified these two, but the `i-i-o-oscilloscope` formula is busted, see below:

Some improvements:

1. I couldn't find a reason to use `ENV.deparallelize` so I re-enabled it.
2. I removed a handful of build dependencies that didn't seem necessary (e.g., `bison` doesn't actually seem to be needed)
3. I made `make install` not attempt to install to `/Library` because that wasn't permitted; instead they install to the package's keg.
4. I made `libad9361-iio` properly declare its dependency on `libiio` so that when installing one, the dependencies are automatically sastisfied.
5. I cleaned up how `cmake` is invoked, following brew's own core formulae (e.g., passing default args).

Things that need to be improved:

1. I didn't have time to fix `i-i-o-oscilloscope` to find its dependencies in their kegs and apply the same improvements.
2. I didn't see if `keg-only` is really a necessary option.
3. The frameworks that are built are kind of bizarre, for instance they have command-line binaries inside them. I don't know if these should be linked into /usr/local/bin?
4. Almost all of the dependencies are declared as `:build` but I don't think that is correct. Probably many of them are runtime dependencies.

**Comment by tfcollins** [comment]
kk thanks for the info. To be honest, the libiio and libad9361 formulae were super WIP. This is why travis-ci was just testing IIO-Scope. For IIO-Scope this was working fine with Catalina when the external dependencies libiio and libad9361 were installed. At least with the release specified. Anyway, I need to switch things to GH Actions for CI here as well. For the keg-only build do you just run:
```
brew install -v --build-from-source <formula>
brew test <formula>
```
Maybe I can add that in and you can rebase.

**Comment by rgov** [comment]
Ok I have had time to sit down and improve this. Sorry it was not great before. The new formulae now build and install both libraries and the main `osc` tool fine.

Unfortunately, in the latest release (v0.11) `osc` crashes on Big Sur after selecting your device, I think due to this issue in another package: https://gitlab.freedesktop.org/cairo/cairo/-/issues/420 This is not a regression caused by this patch.

Forget about the keg-only stuff I was talking about. For the record I don't think my diagnosis of why it couldn't install into /Library/Frameworks was correct — I suspect now it is Homebrew's own sandbox profile that was restricting it.

If you accept this patch, please update references in your wiki etc. to the `i-i-o-oscilloscope` formula to reference `iio-oscilloscope`.

Closes #1. Closes #5.

**Comment by rgov** [comment]
Also included in this pull request is a change from Travis CI to GitHub's built in CI system. The new CI configuration tests all 3 packages on macOS Catalina (10.15). Closes #8.

I was unable to test on Big Sur because Homebrew complains that the default Big Sur system image contains an outdated Xcode.

I also wanted to try running `brew audit` as part of CI but I hit some Ruby issues. Something to revisit in the future, I suppose.

**Comment by rgov** [comment]
I also have a formula for `gr-iio` but it is blocked by this issue: https://github.com/Homebrew/homebrew-core/issues/65387

**Comment by tfcollins** [comment]
Thanks for the update! Had some internet issues last week but I'll review this in the next couple days.

**Pull request merged**
